language: python
python:
  - 2.7
env: 
  global: 
    secure: YFz8YwSqTgG8nGQxmiMYR1JkcfTsCzUJGssf+bfTzJGwK/mcBx/pJE5fD7iktEwsIlPaYlfnM4mKzjjfAVjD5Cmx5aB6BsD5KZmwqlZq9VU6GhYjA3glS0Dnlk7kX80+4UI+YZtOfGroQzeu4TUczrSBbRt8rG1zz/4E+zHi2e0=
install:
  # Dependencies
    - pip install -r requirements.txt --use-mirrors --quiet
    - npm install
    # Workaround https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  # Lint
    - pylint --errors-only --rcfile=.pylintrc python/depict/
    - npm run-script lint
  # Unit test
    - nosetests --config .noserc python/
    - npm test
  # Build
    - rm -rf python/build
    - python python/setup.py sdist
  # Install
    - python python/setup.py install
  # Integration test
    - behave -t ~performance
after_success:
  # Report
    - coveralls
  # Update gh-pages
    - bash update-gh-pages.sh
