language: python
python:
  - 2.7
install:
  # Dependencies
    - pip install -r requirements.txt --use-mirrors --quiet
    - npm install
    # Workaround https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  # Lint
    - pylint --errors-only --rcfile=.pylintrc python/depict/
    - npm run-script lint
  # Unit test
    - nosetests --config .noserc python/
    - npm test
  # Build
    - python python/setup.py sdist
  # Install
    - python python/setup.py install
  # Integration test
    - behave -t ~performance
after_success:
  # Report
    - coveralls

