language: python
python:
  - "2.7"
install:
  - pip install -r python/requirements --use-mirrors
  - npm install
script:
  - pylint --rcfile=python/src/.pylintrc python/src/depict/
  - nosetests --config .noserc python/src/
  - npm test
after_success:
  - coveralls
