language: python
python:
  - 2.7
install:
  # Dependencies
    - pip install -r requirements.txt --use-mirrors --quiet
    - pip install -r dissect-requirement.txt --index-url=https://testpypi.python.org/pypi --extra-index-url=https://pypi.python.org/pypi
    - npm install
    # Workaround https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  # Lint
    - pylint --errors-only --rcfile=.pylintrc python/depict/
    - npm run-script lint
  # Unit test
    - nosetests --config .noserc python/depict
    - npm test
  # Build
    - rm -rf build
    - python setup.py sdist
  # Install
    - python setup.py install
  # Functional test
    - behave test/integration/features
    - behave test/system/features
after_success:
  # Report
    - coveralls
  # Update gh-pages
    - bash update-gh-pages.sh
