language: python
python:
  - 2.7
install:
  # Dependencies
    - pip install -r requirements.txt --use-mirrors --quiet
    - npm install
script:
  # Lint
    - pylint --errors-only --rcfile=.pylintrc python/depict/
    - npm run-script lint
  # Unit test
    - nosetests --config .noserc python/
    - npm test
  # Build
    - python python/setup.py sdist
  # Install
    - python python/setup.py install
  # Integration test
    - behave -t ~performance
after_success:
  # Report
    - coveralls

