language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - npm install
script:
  - pylint --rcfile=python/src/.pylintrc python/src/depict/
  - nosetests --config .noserc python/src/
  - npm test
  - python python/src/setup.py sdist install
after_success:
  - coveralls
