language: python
python:
    - 2.7
env:
  global:
    secure: YFz8YwSqTgG8nGQxmiMYR1JkcfTsCzUJGssf+bfTzJGwK/mcBx/pJE5fD7iktEwsIlPaYlfnM4mKzjjfAVjD5Cmx5aB6BsD5KZmwqlZq9VU6GhYjA3glS0Dnlk7kX80+4UI+YZtOfGroQzeu4TUczrSBbRt8rG1zz/4E+zHi2e0=
before_install:
  # Start x session for splinter. Ref http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
  # Dependencies
    - test -d pip.cache || git clone git://github.com/qdamian/depict.pip.cache pip.cache
    - pip install --no-index --find-links=pip.cache -r requirements.txt -r dev-requirements.txt --quiet
    - pip install -r requirements.txt --use-mirrors --quiet
    - pip install 'dissect >=0.0.dev0' --use-mirrors
                                       --index-url=https://testpypi.python.org/pypi
                                       --extra-index-url=https://pypi.python.org/pypi
    - npm install
  # Workaround https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  # Lint
    - pylint --errors-only --rcfile=.pylintrc depict/
    - npm run-script lint
  # Unit test
    - nosetests --config .noserc depict
    - npm test
  # Build
    - rm -rf build
    # setuptools/distutils only include files under version control. adding JS, css, etc.
    - git ls-files --others --exclude-from=.git/info/exclude depict/html5/ > ignored_files
    - cat ignored_files | xargs git add --force
    - python setup.py build
    - cat ignored_files | xargs git reset || true
    - rm -f ignored_files
  # Install
    - python setup.py install
  # Functional test
    - cd test && behave integration/features --tags=~superseded
    - cd test && behave system/features --tags=~superseded
after_success:
  # Report
  #  - coveralls
  # Update gh-pages
    - bash demo/update-gh-pages.sh
